In [1]:
import numpy as np

In [2]:
data = np.array([[1,2,3],[4,5,6]])
print(data)

[[1 2 3]
 [4 5 6]]


In [3]:
print(data.shape)
print(data.ndim)
print(data.size)
print(data.dtype)

(2, 3)
2
6
int64


In [4]:
print(data[0,1])
print(data[1,1])

2
5


In [5]:
data[0,2]=90
print(data)

[[ 1  2 90]
 [ 4  5  6]]


In [6]:
print(np.sum(data))

108


In [7]:
print(np.sum(data,axis=0))

[ 5  7 96]


In [8]:
print(np.sum(data,axis=1))

[93 15]


In [10]:
array= np.array([[1,2],[3,4],[5,6]])
print(array)

[[1 2]
 [3 4]
 [5 6]]
